### ISSUE TITLE
Does this framework suitable for VoIP audio processing?

### ISSUE THREAD

**Issue by liwei46** [AudioProcessingFramework/apf#6]
Hello,

Thanks for open source your good work. I am trying to use it for VoIP project, which includes some decoing, echo cancellation etc. 

Do you think it is feasible? 
Thanks a lot. 

Regards,

**Comment by mgeier** [comment]
The main usage scenario is if you have many (tens, probably even hundreds)
input and/or output channels and if you want to do some of the audio
processing in parallel on multiple cores.
You'll have to implement all of the VoIP-specific stuff on your own (or use
some other library for that).

If you only want to handle mono/stereo signals (which I guess is typical
for VoIP), the APF doesn't really give you an advantage, so you probably
shouldn't use it.

**Comment by liwei46** [comment]
Hi mgeier,

Thanks a lot for the reply. 
Regards,
